### ISSUE TITLE
Example UI crashes when connect

### ISSUE THREAD

**Issue by xiaohanzhu** [ChainSafe/chainbridge-ui#242]
After updating the chainbridge-runtime-config.evm.js to the following to match my test configuration, I rebuild the example UI with yarn build and yarn start.  
In Metamask I was in rinkeby and the example UI immediately crashes with the attached error

window.__RUNTIME_CONFIG__ = {
  INDEXER__URL: "http://localhost:8000",
  CHAINBRIDGE: {
    chains: [
      {
        domainId: 1,
        networkId: 4,
        name: "Ethereum - Rinkeby",
        decimals: 18,
        bridgeAddress: "0x48a23CB0a361D906BD52BBE6c1eaa8c7eF5Fe8dA",
        erc20HandlerAddress: "0x1d14Bc9615cD06cAa7d04dab2AccBdd7cbbc1861",
        rpcUrl: "I put my Infura URL here",
        type: "Ethereum",
        nativeTokenSymbol: "ETH",
        tokens: [
          {
            address: "0xD6e761838cC5F94e1C2453331ed48DFfaE8c019B",
            name: "an ERC20",
            symbol: "ERC20",
            imageUri: "WETHIcon",
            resourceId:
              "0x000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69500",
          },
        ],
      },
      {
        domainId: 3,
        networkId: 83,
        name: "Ethereum - Goerli",
        decimals: 18,
        bridgeAddress: "0xBFa1654352e2E3A75F4F59572afcbA3e3E694572",
        erc20HandlerAddress: "0x43727c35e6B91f8564240F6627449a747B066647",
        rpcUrl: "https://rpctest.meter.io",
        type: "Ethereum",
        nativeTokenSymbol: "ETH",
        tokens: [
          {
            address: "0xb518b34D9ffD86931d3b6fe0D8c4Ae62E0ccE07c",
            name: "an ERC20",
            symbol: "ERC20",
            imageUri: "WETHIcon",
            resourceId:
              "0x000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69500",
          },
        ],
      },
    ],
  },
};

![image](https://user-images.githubusercontent.com/9540395/169629422-2cb8ef4b-1f82-4897-a0f4-efca9779aa15.png)

**Comment by ss22219** [comment]
TransferPage.tsx:137 
        
       Uncaught TypeError: destinationChains.map is not a function
    at TransferPage (TransferPage.tsx:137:40)
    at renderWithHooks (react-dom.development.js:14803:18)
    at updateFunctionComponent (react-dom.development.js:17034:20)
    at beginWork (react-dom.development.js:18610:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:16)
    at invokeGuardedCallback (react-dom.development.js:292:31)
    at beginWork$1 (react-dom.development.js:23203:7)
    at performUnitOfWork (react-dom.development.js:22157:12)
    at workLoopSync (react-dom.development.js:22130:22)
    at performSyncWorkOnRoot (react-dom.development.js:21756:9)
    at react-dom.development.js:11089:24
    at unstable_runWithPriority (scheduler.development.js:653:12)
    at runWithPriority$1 (react-dom.development.js:11039:10)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:7)
    at flushSyncCallbackQueue (react-dom.development.js:11072:3)
    at flushPassiveEffectsImpl (react-dom.development.js:22883:3)
    at unstable_runWithPriority (scheduler.development.js:653:12)
    at runWithPriority$1 (react-dom.development.js:11039:10)
    at flushPassiveEffects (react-dom.development.js:22820:12)
    at react-dom.development.js:22699:11
    at workLoop (scheduler.development.js:597:34)
    at flushWork (scheduler.development.js:552:16)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164:27)

**Comment by ss22219** [comment]
It looks like the configuration file read failed
